from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent


def _launcher_cmd_text() -> str:
    app_dir = str(ROOT)
    pyw = str(ROOT / "Launch Lab Viewer.pyw")
    return f"""@echo off
rem Auto-generated by launch_sync.py. Keep this launcher pointed at the active app copy.
set "APP_DIR={app_dir}"
cd /d "%APP_DIR%"
if not exist "logs" mkdir "logs"
> "logs\\last_cmd_launch_path.txt" echo APP_DIR=%APP_DIR%

where pythonw.exe >nul 2>nul
if errorlevel 1 (
    echo Could not find pythonw.exe.
    echo.
    echo Try double-clicking "Launch Lab Viewer.pyw" directly, or install Python with pyw support.
    pause
    exit /b 1
)

start "" pythonw.exe "{pyw}"
"""


def known_launcher_paths() -> list[Path]:
    return [
        ROOT / "Launch Lab Viewer.cmd",
    ]


def ensure_launch_cmds() -> None:
    desired = _launcher_cmd_text()
    for path in known_launcher_paths():
        try:
            if path.parent.exists() and (not path.exists() or path.read_text(encoding="utf-8") != desired):
                path.write_text(desired, encoding="utf-8")
        except Exception as exc:
            print(f"[LAUNCH_SYNC] Could not update {path}: {exc}")
