@echo off
rem Auto-generated by launch_sync.py. Keep this launcher pointed at the active app copy.
set "APP_DIR=C:\Users\silam\OneDrive\Documents\Lab viewer\HVAC_Dev\V4\Labview-new_rev"
cd /d "%APP_DIR%"
if not exist "logs" mkdir "logs"
> "logs\last_cmd_launch_path.txt" echo APP_DIR=%APP_DIR%

where pythonw.exe >nul 2>nul
if errorlevel 1 (
    echo Could not find pythonw.exe.
    echo.
    echo Try double-clicking "Launch Lab Viewer.pyw" directly, or install Python with pyw support.
    pause
    exit /b 1
)

start "" pythonw.exe "C:\Users\silam\OneDrive\Documents\Lab viewer\HVAC_Dev\V4\Labview-new_rev\Launch Lab Viewer.pyw"
