@echo off
rem Auto-generated by launch_sync.py. Keep this launcher pointed at the active app copy.
set "APP_DIR=C:\Users\silam\OneDrive\Documents\Lab viewer\HVAC_Lab_Viewer_App"
cd /d "%APP_DIR%"

where pythonw.exe >nul 2>nul
if errorlevel 1 (
    echo Could not find pythonw.exe.
    echo.
    echo Try double-clicking "Launch Lab Viewer.pyw" directly, or install Python with pyw support.
    pause
    exit /b 1
)

start "" pythonw.exe "C:\Users\silam\OneDrive\Documents\Lab viewer\HVAC_Lab_Viewer_App\Launch Lab Viewer.pyw"
